import Image from "next/image"
import Link from "next/link"
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Link href="/">
          <Image
          src="/img/AJOU_LOGO.png"
          width={100}
          height={100}
          alt="AjouLogo"
          />
        </Link>
        <Link href="/ultra/profile">
          .최유정
        </Link>
        <Link  href="/ultra/course">
          코스   
        </Link>
        <Link  href="/ultra/organization">
          조직  
        </Link>
        <Link  href="/ultra/calendar">
          캘린더  
        </Link>
        <Link href="/ultra/messages">
          메시지  
        </Link>
        {children}
      </body>
    </html>
  )
}
